### ISSUE TITLE
Different filenames for Managed Disk Module

### ISSUE THREAD

**Issue by rdtechie** [Azure/azure_preview_modules#246]
I noticed that in Ansible 2.7.x vs. 2.8 that the filename for the managed disk module has been changed from azure_rm_managed_disk.py to azure_rm_manageddisk.py. Is there a reason for it?

**Comment by Fred-sun** [comment]
@rdtechie Thanks for your reporting!
@yungezz Could you help take a look? Ansible 2.7.x Managed disk module name is different from 2.8 . Thanks!

**Comment by yungezz** [comment]
the reason behind this is to make module name consistent cross azure modules. Currently both azure_rm_managed_disk.py and azure_rm_manageddisk.py works because there's a link between them. we'll sync the renaming for upstream to role in coming weeks. and if you met any broken experience due to the renaming, pls let us know. @zikalino

**Comment by Fred-sun** [comment]
@yungezz Thank you for your explanation! 
@rdtechie Please understand! Thanks!

**Comment by rdtechie** [comment]
Thanks @yungezz & @Fred-sun !
